name:CI/CD - INDT

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Restart Docker
        run: |
          sudo /usr/bin/docker-restart.sh

      -name: Login no Github Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Parar container antigo
        run: |
          docker compose down || true

      - name: Build da image 
        run: |
          docker build -t ghcr.io/Paulo-Lennon/indt:latest

      - name: Push da image para o GHCR
        run: |
          docker push ghcr.io/Paulo-Lennon/indt:latest

      - name: Cria o .env na VM
      run: |
        cat > .env << EOF
        DB_HOST=postgres
        DB_PORT=${{ secrets.DB_PORT }}
        DB_USER=${{ secrets.DB_USER }}
        DB_PASS=${{ secrets.DB_PASS }}
        DB_NAME=${{ secrets.DB_NAME }}
        NODE_ENV=production
        PORT=6060
        JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}
        JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
        EOF

      - name: Subir compose
        run: |
          docker compose up -d --build

      - name: Verificar se o container está rodando
        run: |
          sleep 10
          docker compose ps